
name: create-windows-bundle
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mk-windows-bundle:
    runs-on: windows-2022
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Windows bundle
        run: cmd /c "001_create_windows_bundle.cmd"

#      - name: Compile mathlib4 docs
#        run: cmd /c "002_compile_mathlib4_docs.cmd"

      - name: Download mathlib4 docs
        run: cmd /c "003_download_mathlib4_docs.cmd"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TryLean4Bundle.7z
          path: TryLean4Bundle.7z
          if-no-files-found: error

      - name: Upload to GitHub release
        run: cmd /c "999_upload_to_github_release.cmd"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
