
name: test
on:
  workflow_dispatch:

jobs:
  test-download-mathlib4-docs:
    runs-on: windows-2022
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Test
        run: |
          $OTHER_REPO = "leanprover-community/mathlib4_docs"
          $WF_NAME = "docs.yaml"
          $ARTIFACT_NAME = "github-pages"
          $RUN_ID = & gh run --repo "$OTHER_REPO" list --workflow "$WF_NAME" --json databaseId --jq .[0].databaseId
          Write-Host "RUN_ID = $RUN_ID"
          gh run --repo "$OTHER_REPO" download "$RUN_ID" -n "$ARTIFACT_NAME"
          # List the artifiact directory/files
          cmd /c "dir"
          # test
          $A = "82012aca9087eccd1be07d4acf2e12207e88a92f"
          $B = & gh api "/repos/leanprover-community/mathlib4/commits/$A" --jq ".commit.author.date"
          Write-Host $B
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
